/**
 * Beta-safe invoice PDF rendering, shared by the "Export PDF" endpoint and
 * the email endpoint's attachment. Renders only fields that are actually
 * present on the synced invoice/customer/company rows - nothing here is
 * computed or invented, and this is explicitly NOT a reproduction of an
 * official Sage 50 form (see the footer text below).
 */
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export interface InvoiceDetail {
  id: number;
  sageId: string;
  invoiceNumber: string;
  date: string;
  dueDate: string | null;
  total: number;
  balance: number;
  status: string;
  description?: string | null;
  customerSageId: string | null;
  customerName: string | null;
  customerEmail: string | null;
  customerPhone: string | null;
  customerAddress?: string | null;
  customerCity?: string | null;
  customerProvince?: string | null;
  customerPostalCode?: string | null;
  companyName: string | null;
}

function money(value: number | null | undefined): string {
  const n = typeof value === 'number' && Number.isFinite(value) ? value : 0;
  return n.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
}

function invoiceState(invoice: InvoiceDetail): string {
  if (invoice.balance <= 0) return 'Paid';
  if (invoice.dueDate && Date.parse(invoice.dueDate) < Date.now()) return 'Overdue';
  return 'Open';
}

function billingLines(invoice: InvoiceDetail): string[] {
  const lines: string[] = [];
  if (invoice.customerName) lines.push(invoice.customerName);
  if (invoice.customerAddress) lines.push(invoice.customerAddress);
  const cityLine = [invoice.customerCity, invoice.customerProvince, invoice.customerPostalCode].filter(Boolean).join(', ');
  if (cityLine) lines.push(cityLine);
  if (invoice.customerEmail) lines.push(invoice.customerEmail);
  if (invoice.customerPhone) lines.push(invoice.customerPhone);
  return lines;
}

export async function buildInvoicePdf(invoice: InvoiceDetail): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]); // US Letter
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const ink = rgb(0.13, 0.13, 0.15);
  const muted = rgb(0.45, 0.45, 0.48);
  const { height } = page.getSize();
  let y = height - 56;

  const draw = (text: string, x: number, size: number, f = font, color = ink) => {
    page.drawText(text, { x, y, size, font: f, color });
  };

  draw('SageBridge', 48, 20, bold);
  draw('INVOICE', 612 - 48 - bold.widthOfTextAtSize('INVOICE', 20), 20, bold);
  y -= 30;
  if (invoice.companyName) { draw(invoice.companyName, 48, 11, font, muted); y -= 26; } else { y -= 10; }

  draw(`Invoice ${invoice.invoiceNumber || invoice.sageId}`, 48, 13, bold); y -= 18;
  draw(`Date: ${invoice.date || 'Not supplied'}`, 48, 10, font, muted); y -= 14;
  draw(`Due: ${invoice.dueDate || 'Not supplied'}`, 48, 10, font, muted); y -= 14;
  draw(`Status: ${invoiceState(invoice)}`, 48, 10, font, muted);

  // Bill-to block, right column
  let billY = height - 56 - 30 - 26;
  const bill = billingLines(invoice);
  if (bill.length) {
    page.drawText('Bill To', { x: 340, y: billY, size: 10, font: bold, color: muted });
    billY -= 14;
    for (const line of bill) {
      page.drawText(line, { x: 340, y: billY, size: 10, font, color: ink });
      billY -= 13;
    }
  }

  y -= 36;
  page.drawLine({ start: { x: 48, y }, end: { x: 564, y }, thickness: 1, color: rgb(0.85, 0.85, 0.87) });
  y -= 20;

  // Line items are not part of what SageBridge syncs from Sage 50 today -
  // omit them rather than invent quantities or unit prices.
  draw('Line items are not available: SageBridge does not yet sync individual invoice lines from Sage 50.', 48, 9, font, muted);
  y -= 30;

  page.drawLine({ start: { x: 48, y }, end: { x: 564, y }, thickness: 1, color: rgb(0.85, 0.85, 0.87) });
  y -= 22;

  const totalsRow = (label: string, value: string, size = 11, f = font) => {
    page.drawText(label, { x: 380, y, size, font: f, color: ink });
    page.drawText(value, { x: 564 - f.widthOfTextAtSize(value, size), y, size, font: f, color: ink });
    y -= 18;
  };
  totalsRow('Total', money(invoice.total), 12, bold);
  totalsRow('Balance due', money(invoice.balance), 12, bold);

  const footer = 'Generated by SageBridge from Sage 50 data';
  page.drawText(footer, { x: 48, y: 40, size: 9, font, color: muted });
  page.drawText(new Date().toISOString().slice(0, 10), { x: 564 - font.widthOfTextAtSize(new Date().toISOString().slice(0, 10), 9), y: 40, size: 9, font, color: muted });

  return doc.save();
}
